# -*- coding: utf-8 -*-
"""groomfeatureextract.ipynb

Original file generated by Colab and converted to .py
#takes preprocessed posture tracking data and calculates features for classifier model
"""

#load packages you'll need
import os
import pandas as pd
import numpy as np
import glob
import h5py
import math
import pickle
from scipy.stats import zscore


#load data
datafile = open(r'filename', 'rb')
data = pickle.load(datafile)
h5dataall = data[0]
LEDonall = data[1]
facegroomall = data[2]
bodygroomall = data[3]
pseudogroomall = data[4]
nanlocs = data[5]
velall = data[6]

#choose an animal
animal = '4992'

#get all the data for this animal
facegroom = facegroomall[animal]
bodygroom = bodygroomall[animal]
pseudogroom = pseudogroomall[animal]
LEDon = LEDonall[animal]
joints = h5dataall[animal]
nanloc = nanlocs[animal]
vel = velall[animal]

facestart = facegroom[0::2]
facestop = facegroom[1::2]

bodystart = bodygroom[0::2]
bodystop = bodygroom[1::2]

pstart = pseudogroom[0::2]
pstop = pseudogroom[1::2]

#using groom start and stop times, create a matrix of length = samples (frames) and denote what was happening in that frame
#not grooming = 0
#face grooming = 1
#body grooming  = 2
#pseudogrooming = 3

labels = np.zeros([joints.shape[2], 1])

for f in range(0, len(facestart)):
    startidx = round(40*facestart[f])
    stopidx = round(40*facestop[f])
    labels[startidx:stopidx] = 1

for f in range(0, len(bodystart)):
    startidx = round(40*bodystart[f])
    stopidx = round(40*bodystop[f])
    labels[startidx:stopidx] = 2

for f in range(0, len(pstart)):
    startidx = round(40*pstart[f])
    stopidx = round(40*pstop[f])
    labels[startidx:stopidx] = 3

######### calculate features!! #0=snout 1=bodycenter 2=tailbase 3=pawR 4=pawL
#pawR distance from snout (x)
pawR2snoutx = joints[0,3,:] - joints[0,0,:]

#pawR distance from snout (y)
pawR2snouty = joints[1,3,:] - joints[1,0,:]

#pawL distance from snout (x)
pawL2snoutx = joints[0,4,:] - joints[0,0,:]

#pawL distance from snout (y)
pawL2snouty = joints[1,4,:] - joints[1,0,:]

#body center distance from snout (x)
center2snoutx = joints[0,1,:] - joints[0,0,:]

#body center distance from snout (y)
center2snouty = joints[1,1,:] - joints[1,0,:]

#body center distance from tailbase (x)
center2tailx = joints[0,1,:] - joints[0,2,:]

#body center distance from tailbase (y)
center2taily = joints[1,1,:] - joints[1,2,:]

#snout distance from tailbase (x)
snout2tailx = joints[0,0,:] - joints[0,2,:]

#snout distance from tailbase (y)
snout2taily = joints[1,0,:] - joints[1,2,:]

#angle of snout off body center
snoutangle = np.arctan2([joints[1,0,:]-joints[1,1,:]], [joints[0,0,:]-joints[0,1,:]])
snoutangle = (math.pi/2) - snoutangle.T[:,0]

#angular velocity of snout relative to body center
snoutvel = np.diff(snoutangle)
snoutvel = np.append(snoutvel, snoutvel[-1])

#paw to paw distance (x)
paw2pawx = joints[0,3,:] - joints[0,4,:]

#paw to paw distance (y)
paw2pawy = joints[1,3,:] - joints[1,4,:]

##assemble feature matrix
inputfeatures = np.column_stack((pawR2snoutx, pawR2snouty, pawL2snoutx, pawL2snouty, center2snoutx, center2snouty, center2tailx, center2taily,
                                snout2tailx, snout2taily, snoutangle, snoutvel, paw2pawx, paw2pawx, vel))

#save data
import shutil
savename = '4992modelinputs.pkl'
output = open(savename, 'wb')
pickle.dump([inputfeatures, labels], output)
output.close()